### ISSUE TITLE
Missing license for 3rd party code (Pending-Reboot.ps1)

### ISSUE THREAD

**Issue by exchange12rocks** [Sorrowfulgod/UpdateService#1]
I believe, this code https://github.com/Sorrowfulgod/UpdateService/blob/master/Helpers/Pending-Reboot.ps1 is mostly written by Brian Wilhite (https://gallery.technet.microsoft.com/scriptcenter/Get-PendingReboot-Query-bdb79542) and, therefore, should include MSPL at least.

**Comment by Sorrowfulgod** [comment]
Hi!

It’s true! I include MSPL momently


---
С уважением, Груздов Сергей

**Comment by Sorrowfulgod** [comment]
It's true! Sorry, forgot to insert MSPL, but I correct this. Thanks!
